name: GitHub Secrets

on:
  workflow_dispatch:

env:
  my_top_secret: "${{ secrets.MY_TOP_SECRET }}"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET  }}"            
      - name: Print Secret as an environment variable
        run: |
            echo "MY_TOP_SECRET: $my_top_secret"
      - name: Bash Test Step
        shell: bash
        run: |
          env