name: GitHub Secrets

on:
  workflow_dispatch:

env:
  my-top-secret: "${{ secrets.MY_TOP_SECRET }}"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET  }}"            
      - name: Print Secret as an environment variable
        run: |
            echo "MY_TOP_SECRET: $my-top-secret"